### USER SIGN-UP
POST http://localhost:8080/v1/auth/sign-up
Content-Type: application/json

{
  "user": {
    "username": "testuser2",
    "password": "Test1234!@",
    "slackId": "testslack",
    "role": "USER"
  }
}


### USER SIGN-IN
POST http://localhost:8080/v1/auth/sign-in
Content-Type: application/json

{
  "user": {
    "username": "testuser2",
    "password": "Test1234!@"
  }
}