### GET USER
GET http://localhost:8081/v1/users
Content-Type: application/json


### GET USER Details
GET http://localhost:8081/v1/users/1
Content-Type: application/json


### PUT USER Details
PUT http://localhost:8081/v1/users/1
Content-Type: application/json

{
  "user": {
    "password": "testMod",
    "slackId": "slackMod"
  }
}


### DELETE USER
DELETE http://localhost:8081/v1/users/1
Content-Type: application/json


### GET STORE_RESERVATION
GET http://localhost:8081/v1/users/1/store-reservation
Content-Type: application/json
