spring:
  application:
    name: store-reservation-service
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${POSTGRES_STORE_RESERVATION_DB_PORT}/${POSTGRES_STORE_RESERVATION_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  #      password: systempass

  #  #  더미데이터용 환경설정 *배포시 삭제 필요*
  #  profiles:
  #    active: dev

  # Kafka
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
  instance:
    prefer-ip-address: true