server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          filters:
            - AuthorizationHeaderFilter
          uri: lb://user-service
          predicates:
            - Path=/v1/users/**, /v1/auth/**, /springdoc/openapi3-user-service.json

        # Store-service
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/v1/stores/**,/v1/timeslots/**, /springdoc/openapi3-store-service.json

        # Store-reservation-service
        - id: store-reservation-service
          uri: lb://store-reservation-service
          predicates:
            - Path=/v1/store-reservations/**, /springdoc/openapi3-store-reservation-service.json

        # Product
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v1/products/**, /springdoc/openapi3-product-service.json

        # Product-reservation-service
        - id: product-reservation-service
          uri: lb://product-reservation-service
          predicates:
            - Path=/v1/product-reservations/**, /springdoc/openapi3-product-reservation-service.json

        # Slack
        - id: slack-service
          uri: lb://slack-service
          predicates:
            - Path=/v1/slacks/**, /springdoc/openapi3-slack-service.json

      discovery:
        locator:
          enabled: true

      #loadbalancer:
        #enable: true

jwt:
  secret: ${JWT_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    urls[0]:
      name: user-service
      url: /springdoc/openapi3-user-service.json
    urls[1]:
      name: store-service
      url: /springdoc/openapi3-store-service.json
    urls[2]:
      name: store-reservation-service
      url: /springdoc/openapi3-store-reservation-service.json
    urls[3]:
      name: product-service
      url: /springdoc/openapi3-product-service.json
    urls[4]:
      name: product-reservation-service
      url: /springdoc/openapi3-product-reservation-service.json
    urls[5]:
      name: slack-service
      url: /springdoc/openapi3-slack-service.json

    #    use-root-path: true
    path: /docs