spring:
  application:
    name: product-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PRODUCT_DB_PORT}/${POSTGRES_PRODUCT_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  jwt:
    secret: ${JWT_SECRET_KEY}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  group-configs:
    - group: openapi3-product-service
      paths-to-match:
        - /v1/products/**
      packages-to-scan:
        - com.monkey.productservice.presentation.controller
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs