spring:
  application:
    name: product-reservation-service
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PRODUCT_RESERVATION_DB_PORT}/${POSTGRES_PRODUCT_RESERVATION_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  group-configs:
    - group: openapi3-product-reservation-service
      paths-to-match:
        - /v1/product-reservations/**
      packages-to-scan:
        - com.monkey.productreservationservice.presentation.controller
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs
